version: "3.9"
services:
  backend:
    build:
      context: ./src/SmartDocAI.Web
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./src/SmartDocAI.ReactApp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: smartdoc
      POSTGRES_PASSWORD: smartdoc123
      POSTGRES_DB: smartdocdb
    ports:
      - "5432:5432"
