# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - smartdocai-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore SmartDocAI.sln    

      - name: Build with dotnet
        run: dotnet build ./src/SmartDocAI.Web/SmartDocAI.Web.csproj --configuration Release

      - name: Publish self-contained
        run: dotnet publish ./src/SmartDocAI.Web/SmartDocAI.Web.csproj -c Release -r linux-x64 --self-contained true -o ./publish

      - name: Verify required DLLs
        run: |
          REQUIRED_DLLS=("Microsoft.IdentityModel.Tokens.dll" "Microsoft.IdentityModel.Logging.dll" "System.IdentityModel.Tokens.Jwt.dll")
          for dll in "${REQUIRED_DLLS[@]}"; do
            if ! find ./publish -name "$dll" | grep -q .; then
              echo "❌ Missing required DLL: $dll"
              exit 1
            else
              echo "✅ Found: $dll"
            fi
          done    

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E93C16E57AF145D9B0BB9F5A4600FBB0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65241764F6D647718D62808E3E7E7ABC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4DEFEA4F799D409DBC00BD14FBB7EDAF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smartdocai-backend'
          slot-name: 'Production'
          package: .
          